import { Router, Request, Response } from 'express';
import { generateGif, Provider } from './services/gifGenerator';
import { storage } from './storage'; 
import { GifGenerateRequestSchema, GifSearchResponseSchema, GifErrorResponseSchema } from '../shared/schema';
import { fileTypeFromBuffer } from 'file-type';

/**
 * @file Defines API routes for GIF generation and search history.
 */

const router = Router();

/**
 * @route GET /api/gif/searches
 * @description Retrieves past GIF search queries and their results from storage.
 * Each search result is augmented with an `isExisting: true` flag for client-side differentiation.
 * @returns {Response} JSON array of past GIF searches or an error message.
 */
router.get('/api/gif/searches', async (req: Request, res: Response) => {
  try {
    const searches = await storage.getGifSearches();
    res.json(searches.map(s => ({ ...s, isExisting: true }))); 
  } catch (error) {
    console.error('Error fetching GIF searches:', error);
    const errorResponse: GifErrorResponseSchema = { error: 'Failed to fetch GIF searches' };
    res.status(500).json(errorResponse);
  }
});

/**
 * @route POST /api/gif/generate
 * @description Handles requests to generate a new GIF. It parses the request,
 * calls the `generateGif` service, processes the resulting buffers into Base64 data URLs,
 * saves the search to storage, and returns the GIF details to the client.
 * @param {Request} req - The Express request object. Expected body should match `GifGenerateRequestSchema`.
 * @param {Response} res - The Express response object.
 * @returns {Response} JSON response containing the generated GIF's data URLs and metadata,
 * or an error message.
 */
router.post('/api/gif/generate', async (req: Request, res: Response) => {
  console.log('Received /api/gif/generate request with body:', req.body);
  try {
    const parseResult = GifGenerateRequestSchema.safeParse(req.body);
    if (!parseResult.success) {
      console.error('Invalid request body:', parseResult.error.flatten());
      const errorResponse: GifErrorResponseSchema = { 
        error: 'Invalid request body', 
        details: parseResult.error.flatten() 
      };
      return res.status(400).json(errorResponse);
    }

    // Extract validated data. frameCount and gifOptions will be undefined if not provided by client,
    // allowing generateGif to use its defaults.
    const { query, provider = 'auto', frameCount, gifOptions } = parseResult.data;

    console.log(`Generating GIF for query: "${query}", provider: "${provider}"`);

    const generationResult = await generateGif(
        query, 
        provider as Provider, // Type assertion as schema might allow 'auto' string
        frameCount, 
        gifOptions  
    );

    // Unused variables from generationResult (generatedPrompts, imageUrls) are intentionally not destructured
    // to avoid "unused variable" linting issues if they are not part of the final response or extended logging.
    const { gifBuffer, thumbnailBuffer, provider: actualProvider, originalPrompt } = generationResult;

    const gifDataUrl = `data:image/gif;base64,${gifBuffer.toString('base64')}`;

    let thumbnailMimeType = 'image/png'; // Default MIME type
    try {
      const fileTypeResult = await fileTypeFromBuffer(thumbnailBuffer);
      if (fileTypeResult) {
        thumbnailMimeType = fileTypeResult.mime;
        console.log(`Detected thumbnail MIME type: ${thumbnailMimeType}`);
      } else {
        console.warn('Could not detect thumbnail MIME type, defaulting to image/png.');
      }
    } catch (error) {
      console.error('Error detecting thumbnail MIME type:', error);
      console.warn('Proceeding with default image/png for thumbnail.');
    }
    const thumbnailDataUrl = `data:${thumbnailMimeType};base64,${thumbnailBuffer.toString('base64')}`;

    try {
      await storage.createGifSearch({
        query: originalPrompt,
        provider: actualProvider,
        gifUrl: gifDataUrl, 
        thumbnailUrl: thumbnailDataUrl, 
      });
      console.log(`GIF search for "${originalPrompt}" (provider: ${actualProvider}) saved to database.`);
    } catch (dbError) {
      console.error('Error saving GIF search to database:', dbError);
      // Non-critical for client, log and continue.
    }
    
    const responsePayload: GifSearchResponseSchema = {
      // Assuming id is auto-generated by DB and not immediately needed for this response.
      // If createGifSearch returned the new object with id, it could be used here.
      id: Date.now(), // Using timestamp as a temporary unique_ish id for client if needed
      query: originalPrompt,
      provider: actualProvider,
      gifUrl: gifDataUrl,
      thumbnailUrl: thumbnailDataUrl,
      createdAt: new Date().toISOString(), 
      isExisting: false,
    };

    console.log(`Successfully generated GIF for prompt: "${originalPrompt}". Returning data URLs.`);
    res.status(201).json(responsePayload);

  } catch (error) {
    console.error('Error generating GIF:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred during GIF generation.';
    const errorResponse: GifErrorResponseSchema = { error: message };
    // Avoid sending stack traces in production responses
    // if (process.env.NODE_ENV === 'development' && error instanceof Error && error.stack) {
    //     errorResponse.details = { stack: error.stack };
    // }
    res.status(500).json(errorResponse);
  }
});

/**
 * @description Fallback middleware for handling 404 Not Found errors.
 * This should be the last middleware added to the router.
 */
router.use((req: Request, res: Response) => {
  const errorResponse: GifErrorResponseSchema = { error: 'Not Found' };
  res.status(404).json(errorResponse);
});

export default router;
