import {
  generateGoogleAnimationFramesFlow,
  // generateGoogleImageFlow, // Available if single image GIF is an option
} from './google';
import {
  generateOpenAIAnimationFramesFlow,
  // generateOpenAIImageFlow,
} from './openai';
import {
  generateAnthropicAnimationFramesFlow,
  // generateAnthropicImageFlow,
} from './anthropic';
import { createGifFromImageBuffers, GifOptions } from './gifCreator'; // Assuming createGifFromImageBuffers is exported
import { loadImage } from 'canvas'; // For reading dimensions from buffer
import * as z from 'zod'; // For potential schema validation if needed, though flows handle their own.

export type Provider = "auto" | "openai" | "google" | "anthropic";

export interface GenerateGifResult {
  gifBuffer: Buffer;
  thumbnailBuffer: Buffer;
  provider: Provider;
  originalPrompt: string;
  generatedPrompts?: string[]; // Optional: To store prompts used for each frame
  imageUrls?: string[]; // Optional: To store URLs of generated frames
}

const DEFAULT_FRAME_COUNT = 4; // Default number of frames for animation flows
const DEFAULT_GIF_OPTIONS: GifOptions = {
  delay: 200, // ms
  quality: 10, // 1-30 (lower is better)
  repeat: 0,   // 0 for loop indefinitely
};

export async function generateGif(
  prompt: string,
  provider: Provider = "auto",
  frameCount: number = DEFAULT_FRAME_COUNT, // Allow overriding frame count
  gifOptions: GifOptions = DEFAULT_GIF_OPTIONS
): Promise<GenerateGifResult> {
  if (!prompt) {
    throw new Error("Prompt cannot be empty.");
  }

  let actualProvider = provider;
  if (provider === "auto") {
    actualProvider = "google"; // Default to Google if "auto"
    console.log(`generateGif: "auto" provider selected, defaulting to ${actualProvider}.`);
  }

  console.log(`generateGif: Generating GIF for prompt "${prompt}" using ${actualProvider}, ${frameCount} frames.`);

  let frameGenerationResult: Array<{ imageUrl: string; imageBuffer: Buffer; promptUsed: string; }> = [];

  try {
    switch (actualProvider) {
      case "google":
        frameGenerationResult = await generateGoogleAnimationFramesFlow.run({ basePrompt: prompt, frameCount });
        break;
      case "openai":
        frameGenerationResult = await generateOpenAIAnimationFramesFlow.run({ basePrompt: prompt, frameCount });
        break;
      case "anthropic":
        // Anthropic flow returns mock image buffers but real generated prompts
        frameGenerationResult = await generateAnthropicAnimationFramesFlow.run({ basePrompt: prompt, frameCount });
        break;
      default:
        throw new Error(`Unsupported provider: ${actualProvider}`);
    }
  } catch (error) {
    console.error(`generateGif: Error calling Genkit flow for provider ${actualProvider}:`, error);
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to generate frames with ${actualProvider}: ${message}`);
  }

  if (!frameGenerationResult || frameGenerationResult.length === 0) {
    throw new Error(`No frames were generated by ${actualProvider}. Cannot create GIF.`);
  }
  console.log(`generateGif: Successfully generated ${frameGenerationResult.length} frames from ${actualProvider}.`);

  const imageBuffers = frameGenerationResult.map(frame => frame.imageBuffer);
  const generatedPrompts = frameGenerationResult.map(frame => frame.promptUsed);
  const imageUrls = frameGenerationResult.map(frame => frame.imageUrl);

  // Determine width and height from the first image buffer
  let width: number;
  let height: number;
  try {
    const firstImage = await loadImage(imageBuffers[0]); // loadImage from 'canvas'
    width = firstImage.width;
    height = firstImage.height;
    if (width <= 0 || height <= 0) {
        throw new Error(`Invalid dimensions (${width}x${height}) from first frame.`);
    }
    console.log(`generateGif: Determined GIF dimensions from first frame: ${width}x${height}`);
  } catch (error) {
    console.error("generateGif: Error loading first image buffer to determine dimensions:", error);
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to read dimensions from the first generated frame: ${message}`);
  }

  let gifBuffer: Buffer;
  try {
    gifBuffer = await createGifFromImageBuffers(imageBuffers, width, height, gifOptions);
    console.log(`generateGif: GIF created successfully (size: ${gifBuffer.length} bytes).`);
  } catch (error) {
    console.error("generateGif: Error creating GIF from image buffers:", error);
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to create GIF: ${message}`);
  }

  const thumbnailBuffer = imageBuffers[0]; // Use the first frame as the thumbnail

  return {
    gifBuffer,
    thumbnailBuffer,
    provider: actualProvider,
    originalPrompt: prompt,
    generatedPrompts, // Include the prompts used for each frame
    imageUrls,        // Include the URLs for each frame
  };
}

// Example of a more specific GIF generation function if needed in the future
// export async function generateSpecificAnimation(prompt: string): Promise<GenerateGifResult> {
//   // Could call generateGif with specific parameters or have slightly different logic
//   return generateGif(prompt, "openai", 5, { delay: 150, quality: 10 });
// }
