import { render, screen, fireEvent } from '@testing-library/react';
import { Button } from './button'; // Assuming the Button component is in the same directory
import { describe, it, expect, vi } from 'vitest';

describe('Button Component', () => {
  it('renders with children', () => {
    render(<Button>Click Me</Button>);
    const buttonElement = screen.getByRole('button', { name: /Click Me/i });
    expect(buttonElement).toBeInTheDocument();
  });

  it('applies default variant and size if not specified', () => {
    render(<Button>Default</Button>);
    const buttonElement = screen.getByRole('button', { name: /Default/i });
    // Default variant is 'default', default size is 'default'
    // We can check for specific classes if buttonVariants provides them,
    // or rely on visual/snapshot testing for more detailed style checks.
    // For this basic test, presence is sufficient.
    expect(buttonElement).toBeInTheDocument();
  });

  it('applies specified variant', () => {
    render(<Button variant="destructive">Destructive</Button>);
    const buttonElement = screen.getByRole('button', { name: /Destructive/i });
    // Check for a class associated with the destructive variant if possible,
    // e.g., expect(buttonElement).toHaveClass('bg-destructive');
    // This depends on the actual class names generated by cva.
    expect(buttonElement).toBeInTheDocument(); 
  });

  it('applies specified size', () => {
    render(<Button size="lg">Large Button</Button>);
    const buttonElement = screen.getByRole('button', { name: /Large Button/i });
    // Check for a class associated with the large size if possible.
    expect(buttonElement).toBeInTheDocument();
  });

  it('handles click events', () => {
    const handleClick = vi.fn();
    render(<Button onClick={handleClick}>Clickable</Button>);
    const buttonElement = screen.getByRole('button', { name: /Clickable/i });
    fireEvent.click(buttonElement);
    expect(handleClick).toHaveBeenCalledTimes(1);
  });

  it('is disabled when the disabled prop is true', () => {
    const handleClick = vi.fn();
    render(<Button disabled onClick={handleClick}>Disabled</Button>);
    const buttonElement = screen.getByRole('button', { name: /Disabled/i });
    expect(buttonElement).toBeDisabled();
    fireEvent.click(buttonElement);
    expect(handleClick).not.toHaveBeenCalled();
  });

  it('renders as child when asChild prop is true', () => {
    render(
      <Button asChild>
        <a href="/test">Link Button</a>
      </Button>
    );
    // Check if it renders an anchor tag instead of a button
    const linkElement = screen.getByRole('link', { name: /Link Button/i });
    expect(linkElement).toBeInTheDocument();
    expect(linkElement.tagName).toBe('A');
    expect(linkElement).toHaveAttribute('href', '/test');
  });
});
